# $OpenBSD$

COMMENT =				standard client library for many popular cloud providers

MODPY_EGG_VERSION =		0.14.1
DISTNAME =				apache-libcloud-${MODPY_EGG_VERSION}
PKGNAME =				py-libcloud-${MODPY_EGG_VERSION}

HOMEPAGE =				https://libcloud.apache.org/

CATEGORIES =			net devel

# Apache Licence 2.0
PERMIT_PACKAGE_CDROM =	YES

MASTER_SITES =			${MASTER_SITE_PYPI:=a/apache-libcloud/}

MODULES =				lang/python

MODPY_SETUPTOOLS =		Yes

.include <bsd.port.mk>
